### PR TITLE
Add support for @here mentions

### PR DESCRIPTION
**Pull request by janza**

### CODE REVIEW

**Comment by Sorunome** [comment]
matrix does not have `@here`?

**Comment by janza** [comment]
ah, would it be an option to make this behavior configurable then?
eg: with an option in the parser that will determine what kind of broadcast should be sent to slack, as most of the time i want to send a @here broadcast and not a @channel broadcast on slack side

**Comment by Sorunome** [comment]
Are you building something for matrix? (https://matrix.org) if not, it might make sense to generalize this package more in general?

**Comment by Sorunome** [comment]
Or do you mean to configure if @room translates to @channel or @here?

**Comment by janza** [comment]
The latter (the @room behavior)

**Comment by Sorunome** [comment]
Yes, that sounds like a perfectly reasonable PR for this project

**Comment by janza** [comment]
thanks, i've updated the code

**Comment by Sorunome** [comment]
Thanks, done and published at 0.1.8!

**Pull request merged**
